---
title: "Assignment 8"
author: "Lukas Czerwinski"
format: 
  html:
    embed-resources: true
editor: visual
---

```{r, echo=FALSE, message = FALSE,warning = FALSE, include = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(dplyr)
library(tidycensus)
library(osmdata)
library(sf)
library(ggmap)
library(ggthemes)
library(viridis)
library(leaflet)
library(htmltools)


## Load the API key
api_key <- Sys.getenv("MAPS_API_KEY")
```

## Number of Hennepin County Mobile Homes by City
```{r, echo=FALSE, message = FALSE,warning = FALSE, include = FALSE}
#| echo: false
#| message: false
#| warning: false
hen_trailers.df <- get_acs(
  geography = "tract",
  variables = "B11011_006E",
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE,
  cb        = FALSE)


mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)


mn_base.map <- get_map(
  location = hennepin.box,
  source   = "stamen",
  maptype  = "terrain",
  crop = TRUE
)


hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )
hen_trailers_plotly.df <- hen_trailers.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
      map_chr(1) %>%
      str_remove("Census Tract "),
    text_label = str_c(
      "Number of Homes: ",
      estimate
    )
  )
coord_ggmap <- st_crs(hennepin_base.gg) 
coord_sf    <- st_crs(hen_trailers_plotly.df)

hen_trailers.ggmap <- hennepin_base.gg +  
  geom_sf(data = hen_trailers_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1,
          inherit.aes = FALSE) + 
  labs(title = "Hennepin Married Couple Mobile Home Ownership") + 
  scale_fill_viridis_c("Count") +
  theme_map()

hen_trailers.ggmap <- hennepin_base.gg +  
  geom_sf(data = hen_trailers_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1,
          inherit.aes = FALSE) + 
  labs(title = "Hennepin Married Couple Mobile Home Ownership") + 
  scale_fill_viridis_c("Count") +
  theme_map()

map_final <- ggplotly(hen_trailers.ggmap, tooltip = "text") %>%
  style(hoveron = "fills")
```

```{r, echo = FALSE,message = FALSE,warning = FALSE}
map_final
```
